<a href="https://colab.research.google.com/github/be-ayush/ai-ml-learning/blob/main/HOML/HOML3_Chapter9_Artificial_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

iris = load_iris(as_frame=True)

In [2]:
X = iris.data[["petal length (cm)", "petal width (cm)"]].values
Y = (iris.target == 0)

perceptron_classifier = Perceptron(random_state=42)
perceptron_classifier.fit(X, Y)

print(perceptron_classifier.score(X, Y))

X_new = [[2, 0.5], [3, 1]]
y_pred = perceptron_classifier.predict(X_new)
y_pred

1.0


array([ True, False])

In [5]:
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train, X_test, y_train, y_test = train_test_split(
    housing.data, housing.target, random_state=42
)

mlp_regressor = MLPRegressor(hidden_layer_sizes=[50, 50, 50], early_stopping=True, verbose=True, random_state=42)

pipeline = make_pipeline(StandardScaler(), mlp_regressor)
pipeline.fit(X_train, y_train)

Iteration 1, loss = 0.85190332
Validation score: 0.534299
Iteration 2, loss = 0.28288639
Validation score: 0.651094
Iteration 3, loss = 0.22884372
Validation score: 0.699782
Iteration 4, loss = 0.20746145
Validation score: 0.720468
Iteration 5, loss = 0.19649383
Validation score: 0.724839
Iteration 6, loss = 0.18928708
Validation score: 0.740084
Iteration 7, loss = 0.18132029
Validation score: 0.747406
Iteration 8, loss = 0.17556450
Validation score: 0.753945
Iteration 9, loss = 0.17190651
Validation score: 0.760500
Iteration 10, loss = 0.16687650
Validation score: 0.759213
Iteration 11, loss = 0.16329479
Validation score: 0.761907
Iteration 12, loss = 0.16054473
Validation score: 0.768950
Iteration 13, loss = 0.15690181
Validation score: 0.762699
Iteration 14, loss = 0.15630644
Validation score: 0.766003
Iteration 15, loss = 0.15712517
Validation score: 0.778464
Iteration 16, loss = 0.15155981
Validation score: 0.774237
Iteration 17, loss = 0.14957641
Validation score: 0.778361
Iterat

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('mlpregressor',
                 MLPRegressor(early_stopping=True,
                              hidden_layer_sizes=[50, 50, 50], random_state=42,
                              verbose=True))])

In [6]:
mlp_regressor.best_validation_score_

0.791536125425778

In [7]:
y_pred = pipeline.predict(X_test)
rmse = root_mean_squared_error(y_test, y_pred)
rmse

0.5327699946812925

In [8]:
from sklearn.datasets import fetch_openml

fashion_mnist = fetch_openml(name="Fashion-MNIST", as_frame = False)
targets = fashion_mnist.target.astype(int)

In [9]:
X_train, Y_train = fashion_mnist.data[:60000], targets[:60000]
X_test, Y_test = fashion_mnist.data[60000:], targets[60000:]

In [10]:
import plotly.express as px

# Select the first sample from X_train and reshape it to 28x28
sample_image_plotly = X_train[0].reshape(28, 28)

fig = px.imshow(sample_image_plotly, color_continuous_scale='gray')
fig.update_layout(coloraxis_showscale=False) # Hide the color scale
fig.show()

In [11]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
               "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [12]:
class_names[Y_train[0]]

'Ankle boot'

In [13]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler

mlf_classifier = MLPClassifier(hidden_layer_sizes=[300, 100], verbose=True, early_stopping=True, random_state=42)

pipeline = make_pipeline(MinMaxScaler(), mlf_classifier)
pipeline.fit(X_train, Y_train)

Iteration 1, loss = 0.55394420
Validation score: 0.854833
Iteration 2, loss = 0.39017365
Validation score: 0.867500
Iteration 3, loss = 0.34572472
Validation score: 0.877500
Iteration 4, loss = 0.31541926
Validation score: 0.881167
Iteration 5, loss = 0.29351007
Validation score: 0.887167
Iteration 6, loss = 0.28459028
Validation score: 0.889167
Iteration 7, loss = 0.26775210
Validation score: 0.885500
Iteration 8, loss = 0.25610516
Validation score: 0.886667
Iteration 9, loss = 0.24488907
Validation score: 0.893167
Iteration 10, loss = 0.23915583
Validation score: 0.888500
Iteration 11, loss = 0.22290961
Validation score: 0.897167
Iteration 12, loss = 0.21925185
Validation score: 0.889667
Iteration 13, loss = 0.21249406
Validation score: 0.892167
Iteration 14, loss = 0.20374069
Validation score: 0.891333
Iteration 15, loss = 0.19557455
Validation score: 0.893833
Iteration 16, loss = 0.19099949
Validation score: 0.893667
Iteration 17, loss = 0.18445775
Validation score: 0.890333
Iterat

Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                ('mlpclassifier',
                 MLPClassifier(early_stopping=True,
                               hidden_layer_sizes=[300, 100], random_state=42,
                               verbose=True))])

In [15]:
accuracy = pipeline.score(X_test, Y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.8929


In [16]:
X_new = X_test[:15]
y_pred = pipeline.predict(X_new)
y_pred

array([9, 2, 1, 1, 6, 1, 4, 6, 5, 7, 4, 5, 5, 3, 4])

In [20]:
y_proba = mlf_classifier.predict_proba(X_new)
y_proba[12]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [22]:
from sklearn.datasets import fetch_covtype

covtype = fetch_covtype(as_frame=False)

In [25]:
covtype.data.shape

(581012, 54)

In [26]:
covtype.target.shape

(581012,)

In [27]:
covtype.feature_names

['Elevation',
 'Aspect',
 'Slope',
 'Horizontal_Distance_To_Hydrology',
 'Vertical_Distance_To_Hydrology',
 'Horizontal_Distance_To_Roadways',
 'Hillshade_9am',
 'Hillshade_Noon',
 'Hillshade_3pm',
 'Horizontal_Distance_To_Fire_Points',
 'Wilderness_Area_0',
 'Wilderness_Area_1',
 'Wilderness_Area_2',
 'Wilderness_Area_3',
 'Soil_Type_0',
 'Soil_Type_1',
 'Soil_Type_2',
 'Soil_Type_3',
 'Soil_Type_4',
 'Soil_Type_5',
 'Soil_Type_6',
 'Soil_Type_7',
 'Soil_Type_8',
 'Soil_Type_9',
 'Soil_Type_10',
 'Soil_Type_11',
 'Soil_Type_12',
 'Soil_Type_13',
 'Soil_Type_14',
 'Soil_Type_15',
 'Soil_Type_16',
 'Soil_Type_17',
 'Soil_Type_18',
 'Soil_Type_19',
 'Soil_Type_20',
 'Soil_Type_21',
 'Soil_Type_22',
 'Soil_Type_23',
 'Soil_Type_24',
 'Soil_Type_25',
 'Soil_Type_26',
 'Soil_Type_27',
 'Soil_Type_28',
 'Soil_Type_29',
 'Soil_Type_30',
 'Soil_Type_31',
 'Soil_Type_32',
 'Soil_Type_33',
 'Soil_Type_34',
 'Soil_Type_35',
 'Soil_Type_36',
 'Soil_Type_37',
 'Soil_Type_38',
 'Soil_Type_39']

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    covtype.data, covtype.target, random_state=42
)

X_train.shape

(435759, 54)

In [29]:
y_train[:10]

array([2, 2, 2, 1, 1, 1, 1, 1, 2, 1], dtype=int32)

In [30]:
y_train[:100]

array([2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 5, 3, 1, 2, 2, 2,
       1, 1, 3, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 7, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 3, 5, 2,
       2, 1, 3, 7, 2, 1, 1, 1, 2, 3, 3, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1,
       6, 1, 2, 3, 2, 2, 2, 2, 2, 1, 7, 1], dtype=int32)

In [31]:
import numpy as np

num_unique_classes = len(np.unique(covtype.target))
print(f"Number of unique classes in covtype.target: {num_unique_classes}")

Number of unique classes in covtype.target: 7


In [36]:
covtype_mlp_classifier = MLPClassifier(hidden_layer_sizes=[200, 100, 50], verbose=True, early_stopping=True, random_state=42)
covtype_pipeline = make_pipeline(StandardScaler(), covtype_mlp_classifier)
covtype_pipeline.fit(X_train, y_train)

Iteration 1, loss = 0.54176112
Validation score: 0.806751
Iteration 2, loss = 0.42014984
Validation score: 0.830847
Iteration 3, loss = 0.36860865
Validation score: 0.853589
Iteration 4, loss = 0.33598244
Validation score: 0.864536
Iteration 5, loss = 0.31272332
Validation score: 0.869768
Iteration 6, loss = 0.29537023
Validation score: 0.884111
Iteration 7, loss = 0.28015485
Validation score: 0.883284
Iteration 8, loss = 0.26937433
Validation score: 0.888126
Iteration 9, loss = 0.26004990
Validation score: 0.893129
Iteration 10, loss = 0.25201742
Validation score: 0.892188
Iteration 11, loss = 0.24352796
Validation score: 0.898476
Iteration 12, loss = 0.23721328
Validation score: 0.901941
Iteration 13, loss = 0.23194199
Validation score: 0.904053
Iteration 14, loss = 0.22549482
Validation score: 0.905567
Iteration 15, loss = 0.22150953
Validation score: 0.907770
Iteration 16, loss = 0.21765983
Validation score: 0.909606
Iteration 17, loss = 0.21269369
Validation score: 0.906462
Iterat

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('mlpclassifier',
                 MLPClassifier(early_stopping=True,
                               hidden_layer_sizes=[200, 100, 50],
                               random_state=42, verbose=True))])

In [37]:
accuracy = covtype_pipeline.score(X_test, y_test)
accuracy

0.9325521675972269